spring:
  application:
    name:
      demo

  datasource:
    url: "jdbc:oracle:thin:@localhost:1521/FREEPDB1"
    username: hogeuser
    password: passw0rd
    driver-class-name: oracle.jdbc.driver.OracleDriver

