-- PDBへ切り替え
ALTER SESSION SET CONTAINER=FREEPDB1;

-- ユーザ削除
DROP USER hogeuser CASCADE;

-- ユーザ作成
CREATE USER hogeuser IDENTIFIED BY passw0rd
DEFAULT TABLESPACE users
QUOTA UNLIMITED ON users
TEMPORARY TABLESPACE temp;

-- 作成ユーザへ権限付与
GRANT CREATE SESSION TO hogeuser;
GRANT RESOURCE TO hogeuser;
GRANT UNLIMITED TABLESPACE TO hogeuser;
GRANT SELECT_CATALOG_ROLE TO hogeuser;
GRANT SELECT ANY DICTIONARY TO hogeuser;
GRANT SYSDBA TO hogeuser;