version: '3'

services:
  db:
    image: container-registry.oracle.com/database/free:latest
    container_name: oracle21c
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - db-store:/opt/oracle/oradata
      - ./script/startup:/opt/oracle/scripts/startup # 追加
      - ./script/setup:/opt/oracle/scripts/setup  # 追加
    environment:
      - ORACLE_PWD=passw0rd


volumes:
  db-store:
  oracle-emcc2:
   name: oracle-emcc2

networks:
  external:
    external: true
