version: '3'

services:
  db:
    image: oracle/database:21.3.0-xe
    container_name: oracle21c
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - db-store:/opt/oracle/oradata
      - ./script/startup:/opt/oracle/scripts/startup # 追加
      - ./script/setup:/opt/oracle/scripts/setup  # 追加
    environment:
      - ORACLE_PWD=passw0rd

  jenkins:
    image: myjenkins:latest
    container_name: jenkins-blueocean
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home # 追加
      - jenkins-docker-certs:/certs/client:ro  # 追加
    environment:
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      - DOCKER_HOST=tcp://docker:2376


volumes:
  jenkins-data:
  jenkins-docker-certs:
  db-store:
  oracle-emcc2:
   name: oracle-emcc2


