name: CI

on:
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          destribution: 'temurin'

      - name: Set up Docker
        run: sudo apt-get install docker-compose

      - name: Start Container
        run: docker-compose up -d

      - name: Wait DB
        run: sleep 120

      - name: Run Flyway
        run: ./gradlew flywayMigrate

      - name: Run test
        run: ./gradlew test

      - name: Down Container
        run: docker-compose down