name: CI

on:
  pull_request_target:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: list
        run: ls

      - name: Set up Docker
        run: sudo apt-get install docker-compose

      - name: Start Container
        uses: gvenzl/setup-oracle-free@v1
        with: 
          app-user: hogeuser
          app-user-password: passw0rd
          startup-scripts: ./demo/script/startup
          setup-scripts: ./demo/script/setup
          port: 1521

      - name: Wait DB
        run: sleep 90

      - name: Run Flyway
        run: ./gradlew flywayMigrate
        working-directory: ./demo

      - name: Run test
        run: ./gradlew test
        working-directory: ./demo

      - name: Down Container
        run: docker-compose down
        working-directory: ./demo
